name: Deploy application

on:
  repository_dispatch:
    types: [deploy]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print repository_dispatch payload
        run: |
          echo "${{ toJson(github.event.client_payload) }}"

      - name: Simulate a deployment
        run: |
          docker run --rm -e FOOBAR=${{ github.event.client_payload.foobar }} \
            ${{ github.event.client_payload.image_artifact }}
