name: Deploy application

on:
  repository_dispatch:
    types: [deploy]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "repo_dispatch_params|${{ github.event.client_payload.deployment_id }}"
        run: |
          echo "${{ toJson(github.event.client_payload) }}"

      - name: Create environment manifest
        run: |
          mkdir -p ${{ github.event.client_payload.environment_subdir }}
          echo "${{ github.event.client_payload.artifact_url }}" > ${{ github.event.client_payload.environment_subdir }}/deployment.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push

      - name: Login to GitHub Docker Registry
        run: docker login docker.pkg.github.com --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: Simulate a deployment
        run: |
          docker run --rm -e foobar='${{ github.event.client_payload.foobar }}' \
            ${{ github.event.client_payload.artifact_url }}
